CREATE TABLE   E_BOOK  
   (CALLNO  VARCHAR(40), 
	 NAME  VARCHAR(40), 
	 AUTHOR  VARCHAR(40), 
	 PUBLISHER  VARCHAR(40), 
	 QUANTITY  int,
	 ISSUED  int, 
	 PRIMARY KEY ( CALLNO )
   );
CREATE TABLE   E_LIBRARIAN  
   (ID  int, 
	 NAME  VARCHAR(40), 
	 PASSWORD  VARCHAR(40), 
	 EMAIL  VARCHAR(40), 
	 MOBILE  bigint, 
	 PRIMARY KEY ( ID ) 
   );
CREATE TABLE   E_ISSUEBOOK  
   (CALLNO  VARCHAR(40),
	 STUDENTID  VARCHAR(40),
	 STUDENTNAME  VARCHAR(40), 
	 STUDENTMOBILE  bigint, 
	 ISSUEDDATE  DATE, 
	 RETURNSTATUS  VARCHAR(4)
   );
